version = 5.6.0
archive_dir = /etc/letsencrypt/archive/kbook.fssh.khc.edu.tw
cert = /etc/letsencrypt/live/kbook.fssh.khc.edu.tw/cert.pem
privkey = /etc/letsencrypt/live/kbook.fssh.khc.edu.tw/privkey.pem
chain = /etc/letsencrypt/live/kbook.fssh.khc.edu.tw/chain.pem
fullchain = /etc/letsencrypt/live/kbook.fssh.khc.edu.tw/fullchain.pem
[renewalparams]
account = e1664c6be2f9bfff261128f3203f68cb
rsa_key_size = 4096
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
kbook.fssh.khc.edu.tw = /var/www/certbot
